### ISSUE TITLE
影片心得回覆

### ISSUE THREAD

**Issue by azole** [Samyo0608/hello-git#2]
謝謝你的總結，「過程很重要，重要程度甚至超越結果，在過程中才會體驗到失敗，體會到不如預期的事情，所以才會有自己解決問題的機會」這句話真的說太好了，不知道其他領域怎麼樣，我自己覺得在軟體開發這個領域，學習過程真的超級重要的，我經常覺得，學習過程順順的、沒有踩到 bug 的話，其實學到的東西是比較少。在學習過程中遭遇了問題的人，雖然過程很痛苦，但最後收穫反而會是最豐富的。

期待你踩雷的過程 XD，有問題都歡迎找我討論喔，接下來讓我們在上課時一起踩雷吧！

**Comment by Samyo0608** [comment]
好的，謝謝老師認真看完~
